---
#SLURM dependences
- name: '[EL] Install epel repo'
  yum: name=epel-release

- name: '[EL] update repositories cache and yum install slurm dependences in REL systems'
  yum: name=readline-devel,openssl,openssl-devel,munge-devel,pam-devel,perl-ExtUtils-MakeMaker,gcc,make,rpm-build,perl-DBI,psmisc

- name: '[EL] Install perl-Switch in CentOS 7'
  yum: name=perl-Switch
  when: ansible_distribution_major_version == "7"

- name: '[EL] Set Centos 7 facts'
  set_fact:
    SLURM_VERSION: "{{ slurm_version }}-1.el7.centos"
    PKG_FOLDER: "centos7/{{ slurm_version }}"
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int == 7

- name: '[EL] Copy required packages'
  copy: src={{PKG_FOLDER}}/{{item}} dest=/tmp/{{item}}
  with_items:
    - slurm-{{SLURM_VERSION}}.x86_64.rpm
    - slurm-devel-{{SLURM_VERSION}}.x86_64.rpm
    - slurm-munge-{{SLURM_VERSION}}.x86_64.rpm
    - slurm-openlava-{{SLURM_VERSION}}.x86_64.rpm
    - slurm-pam_slurm-{{SLURM_VERSION}}.x86_64.rpm
    - slurm-perlapi-{{SLURM_VERSION}}.x86_64.rpm
    - slurm-plugins-{{SLURM_VERSION}}.x86_64.rpm
    - slurm-seff-{{SLURM_VERSION}}.x86_64.rpm
    - slurm-sjobexit-{{SLURM_VERSION}}.x86_64.rpm
    - slurm-sjstat-{{SLURM_VERSION}}.x86_64.rpm
    - slurm-slurmdb-direct-{{SLURM_VERSION}}.x86_64.rpm
    - slurm-slurmdbd-{{SLURM_VERSION}}.x86_64.rpm
    - slurm-sql-{{SLURM_VERSION}}.x86_64.rpm
    - slurm-torque-{{SLURM_VERSION}}.x86_64.rpm

- name: '[EL] Install rpm slurm packages (common)'
  yum:
    name:
      - "/tmp/slurm-{{SLURM_VERSION}}.x86_64.rpm"
      - "/tmp/slurm-devel-{{SLURM_VERSION}}.x86_64.rpm"
      - "/tmp/slurm-munge-{{SLURM_VERSION}}.x86_64.rpm"
      - "/tmp/slurm-openlava-{{SLURM_VERSION}}.x86_64.rpm"
      - "/tmp/slurm-pam_slurm-{{SLURM_VERSION}}.x86_64.rpm"
      - "/tmp/slurm-perlapi-{{SLURM_VERSION}}.x86_64.rpm"
      - "/tmp/slurm-plugins-{{SLURM_VERSION}}.x86_64.rpm"
      - "/tmp/slurm-seff-{{SLURM_VERSION}}.x86_64.rpm"
      - "/tmp/slurm-sjobexit-{{SLURM_VERSION}}.x86_64.rpm"
      - "/tmp/slurm-sjstat-{{SLURM_VERSION}}.x86_64.rpm"
      - "/tmp/slurm-slurmdb-direct-{{SLURM_VERSION}}.x86_64.rpm"
      - "/tmp/slurm-slurmdbd-{{SLURM_VERSION}}.x86_64.rpm"
      - "/tmp/slurm-sql-{{SLURM_VERSION}}.x86_64.rpm"
      - "/tmp/slurm-torque-{{SLURM_VERSION}}.x86_64.rpm"
  state: present

- set_fact:
    SLURM_CONF: "/etc/slurm/slurm.conf"
    SLURM_SERVICE: "slurm"
  
- name: '[EL] create slurm user and group'
  user: name=slurm shell=/bin/bash system=yes

- name: '[EL] create folders used by SLURM and set slurm owner'
  file: path={{item}} state=directory owner=slurm group=slurm
  with_items:
    - /var/spool/slurm
    - /var/log/slurm
    - /var/slurm/checkpoint
    - /etc/slurm

- name: '[EL] Disable firewall in CentOS 7'
  service: name=firewalld state=stopped enabled=False
  when: ansible_distribution_major_version == "7"
  ignore_errors: yes
